version: "3.5"

services:
  web:
    build: .
    working_dir: /app
    env_file: .env
    command: bin/start_dev
    volumes:
      - .:/app
    ports:
      - '3000:3000'
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password

      