test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

google_dev:
  service: GCS
  project: beekeeper-292318
  credentials: <%= ENV['GOOGLE_APPLICATION_CREDENTIALS'].to_json %>
  bucket: admin-images

google:
  service: GCS
  project: beekeeper-292318
  credentials: <%= ENV['GOOGLE_APPLICATION_CREDENTIALS'].to_json %>
  bucket: admin-images